"""Add explore table

Revision ID: 8d2e9ad6566a
Revises: 0ec6a5d3994c
Create Date: 2024-10-16 23:25:47.883192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2e9ad6566a'
down_revision = '0ec6a5d3994c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trending_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('trending_score')
        batch_op.drop_column('comments_count')

    # ### end Alembic commands ###
